# Generated by Django 2.2 on 2024-08-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_auto_20240809_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='addrees',
            new_name='address',
        ),
    ]
